### ISSUE TITLE
Unclear how to rebuild data

### ISSUE THREAD

**Issue by iamcal** [NooksBazaar/google-sheets-to-json#12]
To pick up new sheet changes, I've been doing this:

```
rm cache/*
bash bin/build.sh (node build)
```

If I don't clear the cache first, it mostly doesn't work.

Since this is a very common action (there are changes every day), it would be good if this was easier and well documented.

**Comment by LavaToaster** [comment]
Ah yeah, the cache is mainly a thing so you aren't consistently hitting google servers to download data whilst playing around with the build script.

It might be a good idea to write some kind of cache buster into it at some point. (Check google sheets for changes first, Limit to once an hour, or a day? )

**Comment by iamcal** [comment]
ahh, that makes sense. maybe something like #13 is a simple start?
